org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version = 1.21.1
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07
jei_version=19.18.1.201

mod_id=create_security
mod_name=Create: Security Program
mod_license=MIT
mod_version=1.21.1-2.0
mod_group_id=org.portality
mod_authors=_Portality_, VladisCrafter, To0pa
mod_description=An add-on for Create mod to secure your factories and add tickets to your train network.
